import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { payrollAPI, employeeAPI, siteAPI } from '@/lib/api';
import { useUIStore } from '@/store/uiStore';
import { Button } from '@/components/ui/Button';
import { Select } from '@/components/ui/Select';
import { Label } from '@/components/ui/Label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Download, FileSpreadsheet, FileText } from 'lucide-react';
import { formatCurrency, downloadFile } from '@/lib/utils';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export function Payroll() {
  const currentDate = new Date();
  const [selectedMonth, setSelectedMonth] = useState(currentDate.getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(currentDate.getFullYear());
  const { showToast } = useUIStore();

  const { data: payrollData, isLoading, error } = useQuery({
    queryKey: ['payroll', selectedYear, selectedMonth],
    queryFn: async () => {
      const res = await payrollAPI.calculate(selectedYear, selectedMonth);
      return res.data;
    },
    enabled: !!selectedYear && !!selectedMonth,
  });

  const { data: sites = [] } = useQuery({
    queryKey: ['sites'],
    queryFn: async () => {
      const res = await siteAPI.getAll();
      return res.data;
    },
  });

  const exportToPDF = () => {
    if (!payrollData) return;

    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(18);
    doc.text('Monthly Payroll Report', 14, 20);
    
    // Month/Year
    doc.setFontSize(12);
    doc.text(`Month: ${format(new Date(selectedYear, selectedMonth - 1), 'MMMM yyyy')}`, 14, 30);
    doc.text(`Generated: ${format(new Date(), 'dd/MM/yyyy HH:mm')}`, 14, 37);
    doc.text(`Generated By: ${payrollData.generatedBy}`, 14, 44);
    
    // Summary
    doc.text(`Total Employees: ${payrollData.totalEmployees}`, 14, 54);
    doc.text(`Total Amount: ${formatCurrency(payrollData.totalAmount)}`, 14, 61);

    // Table
    const tableData = payrollData.payroll.map(item => [
      item.employeeName,
      item.profession,
      item.presentDays.toFixed(1),
      item.totalOtHours.toFixed(1),
      formatCurrency(item.daySalary),
      formatCurrency(item.otSalary),
      formatCurrency(item.totalSalary),
    ]);

    doc.autoTable({
      startY: 70,
      head: [['Name', 'Profession', 'Days', 'OT Hrs', 'Day Salary', 'OT Salary', 'Total']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
      foot: [[
        'TOTAL',
        '',
        '',
        '',
        '',
        '',
        formatCurrency(payrollData.totalAmount)
      ]],
      footStyles: { fillColor: [229, 231, 235], textColor: [0, 0, 0], fontStyle: 'bold' },
    });

    // Signature area
    const finalY = doc.lastAutoTable.finalY || 70;
    doc.text('Manager Signature: _______________________', 14, finalY + 20);
    doc.text('Date: _______________________', 14, finalY + 30);

    doc.save(`Payroll_${selectedYear}_${String(selectedMonth).padStart(2, '0')}.pdf`);
    showToast({ message: 'PDF downloaded successfully', type: 'success' });
  };

  const exportToExcel = () => {
    if (!payrollData) return;

    const data = payrollData.payroll.map(item => ({
      'Employee Name': item.employeeName,
      'Profession': item.profession,
      'Present Days': item.presentDays,
      'Absent Days': item.absentDays,
      'Half Days': item.halfDays,
      'OT Hours': item.totalOtHours,
      'Per Day Salary': item.perDaySalary,
      'Per Hour Salary': item.perHourSalary,
      'Day Salary': item.daySalary,
      'OT Salary': item.otSalary,
      'Total Salary': item.totalSalary,
    }));

    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Payroll');

    XLSX.writeFile(wb, `Payroll_${selectedYear}_${String(selectedMonth).padStart(2, '0')}.xlsx`);
    showToast({ message: 'Excel downloaded successfully', type: 'success' });
  };

  const months = [
    { value: 1, label: 'January' },
    { value: 2, label: 'February' },
    { value: 3, label: 'March' },
    { value: 4, label: 'April' },
    { value: 5, label: 'May' },
    { value: 6, label: 'June' },
    { value: 7, label: 'July' },
    { value: 8, label: 'August' },
    { value: 9, label: 'September' },
    { value: 10, label: 'October' },
    { value: 11, label: 'November' },
    { value: 12, label: 'December' },
  ];

  const years = Array.from({ length: 5 }, (_, i) => currentDate.getFullYear() - i);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">Payroll</h1>
          <p className="text-muted-foreground mt-1">
            Calculate and export monthly payroll
          </p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1">
              <Label htmlFor="month">Month</Label>
              <Select
                id="month"
                value={selectedMonth}
                onChange={(e) => setSelectedMonth(parseInt(e.target.value))}
              >
                {months.map(month => (
                  <option key={month.value} value={month.value}>
                    {month.label}
                  </option>
                ))}
              </Select>
            </div>
            <div className="flex-1">
              <Label htmlFor="year">Year</Label>
              <Select
                id="year"
                value={selectedYear}
                onChange={(e) => setSelectedYear(parseInt(e.target.value))}
              >
                {years.map(year => (
                  <option key={year} value={year}>
                    {year}
                  </option>
                ))}
              </Select>
            </div>
            <div className="flex gap-2 items-end">
              <Button onClick={exportToPDF} disabled={!payrollData || isLoading}>
                <FileText className="h-4 w-4 mr-2" />
                PDF
              </Button>
              <Button onClick={exportToExcel} disabled={!payrollData || isLoading}>
                <FileSpreadsheet className="h-4 w-4 mr-2" />
                Excel
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="text-center py-8 text-muted-foreground">Calculating payroll...</div>
          ) : error ? (
            <div className="text-center py-8 text-destructive">
              Failed to calculate payroll: {error.message}
            </div>
          ) : !payrollData || payrollData.payroll.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              No attendance data for this period
            </div>
          ) : (
            <div>
              {/* Summary */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6 p-4 bg-muted rounded-lg">
                <div>
                  <p className="text-sm text-muted-foreground">Total Employees</p>
                  <p className="text-2xl font-bold">{payrollData.totalEmployees}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Total Amount</p>
                  <p className="text-2xl font-bold">{formatCurrency(payrollData.totalAmount)}</p>
                </div>
                <div>
                  <p className="text-sm text-muted-foreground">Generated By</p>
                  <p className="text-lg font-medium">{payrollData.generatedBy}</p>
                </div>
              </div>

              {/* Payroll Table */}
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b text-left text-sm text-muted-foreground">
                      <th className="pb-3 font-medium">Employee</th>
                      <th className="pb-3 font-medium">Profession</th>
                      <th className="pb-3 font-medium text-center">Present</th>
                      <th className="pb-3 font-medium text-center">Absent</th>
                      <th className="pb-3 font-medium text-center">OT Hrs</th>
                      <th className="pb-3 font-medium text-right">Day Salary</th>
                      <th className="pb-3 font-medium text-right">OT Salary</th>
                      <th className="pb-3 font-medium text-right">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {payrollData.payroll.map(item => (
                      <tr key={item.employeeId} className="border-b hover:bg-muted/50">
                        <td className="py-3 font-medium">{item.employeeName}</td>
                        <td className="py-3">{item.profession}</td>
                        <td className="py-3 text-center">{item.presentDays.toFixed(1)}</td>
                        <td className="py-3 text-center">{item.absentDays}</td>
                        <td className="py-3 text-center">{item.totalOtHours.toFixed(1)}</td>
                        <td className="py-3 text-right">{formatCurrency(item.daySalary)}</td>
                        <td className="py-3 text-right">{formatCurrency(item.otSalary)}</td>
                        <td className="py-3 text-right font-semibold">{formatCurrency(item.totalSalary)}</td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 font-bold">
                      <td className="py-3" colSpan="7">TOTAL</td>
                      <td className="py-3 text-right">{formatCurrency(payrollData.totalAmount)}</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
