import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { attendanceAPI, employeeAPI, payrollAPI, siteAPI } from '@/lib/api';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/Label';
import { FileText, DollarSign, Users, Download, Calendar, Clock } from 'lucide-react';
import { format } from 'date-fns';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

// Format currency in AED (UAE Dirham)
const formatCurrency = (amount) => {
  return `AED ${Number(amount || 0).toFixed(2)}`;
};

export function Reports() {
  const [selectedMonth, setSelectedMonth] = useState(format(new Date(), 'yyyy-MM'));
  const [reportDate, setReportDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  
  const [year, month] = selectedMonth.split('-').map(Number);

  // Fetch data
  const { data: employees = [] } = useQuery({
    queryKey: ['employees'],
    queryFn: async () => {
      const res = await employeeAPI.getAll();
      return res.data;
    },
  });

  const { data: payrollData, isLoading: payrollLoading } = useQuery({
    queryKey: ['payroll', year, month],
    queryFn: async () => {
      const res = await payrollAPI.calculateMonthly(year, month);
      return res.data;
    },
    enabled: !!year && !!month,
  });

  const { data: attendance = [], isLoading: attendanceLoading } = useQuery({
    queryKey: ['attendance', reportDate],
    queryFn: async () => {
      const res = await attendanceAPI.getAll({
        startDate: reportDate,
        endDate: reportDate,
      });
      return res.data;
    },
  });

  const { data: sites = [] } = useQuery({
    queryKey: ['sites'],
    queryFn: async () => {
      const res = await siteAPI.getAll();
      return res.data;
    },
  });

  // Export Attendance Report - Professional Format
  const exportAttendanceReport = () => {
    const pdf = new jsPDF();
    
    // Company Header - Professional Teal
    pdf.setFillColor(20, 83, 89); // Professional teal/dark cyan
    pdf.rect(0, 0, 210, 35, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(20);
    pdf.setFont(undefined, 'bold');
    pdf.text('BAWABT ALMASKAN', 105, 15, { align: 'center' });
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text('REAL ESTATE - Daily Attendance Report', 105, 22, { align: 'center' });
    pdf.text(`Date: ${format(new Date(reportDate), 'dd MMM yyyy')}`, 105, 29, { align: 'center' });
    
    // Reset text color
    pdf.setTextColor(0, 0, 0);

    // Table data
    const tableData = attendance.map(att => {
      const emp = employees.find(e => e.id === att.employeeId);
      const site = sites.find(s => s.id === att.siteId);
      const siteInfo = site ? `${site.siteNumber} - ${site.siteName} (${site.location})` : '-';
      return [
        emp?.name || '-',
        emp?.profession || '-',
        att.status,
        att.otHours || 0,
        siteInfo,
        att.approved ? 'Yes' : 'No',
      ];
    });

    pdf.autoTable({
      head: [['Employee', 'Profession', 'Status', 'OT Hours', 'Site (Number - Name - Location)', 'Approved']],
      body: tableData,
      startY: 42,
      theme: 'striped',
      headStyles: { fillColor: [20, 83, 89], fontSize: 10, fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
    });

    // Footer
    const footerY = pdf.internal.pageSize.height - 15;
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(`Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 105, footerY, { align: 'center' });
    pdf.text('BAWABT ALMASKAN - Confidential Document', 105, footerY + 5, { align: 'center' });

    pdf.save(`Attendance_${reportDate}.pdf`);
  };

  // Export Payroll Report - Professional Format
  const exportPayrollReport = () => {
    if (!payrollData) return;

    const pdf = new jsPDF();
    
    // Company Header - Professional Teal
    pdf.setFillColor(20, 83, 89);
    pdf.rect(0, 0, 210, 35, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(20);
    pdf.setFont(undefined, 'bold');
    pdf.text('BAWABT ALMASKAN', 105, 15, { align: 'center' });
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text('REAL ESTATE - Monthly Payroll Report', 105, 22, { align: 'center' });
    pdf.text(`Period: ${format(new Date(year, month - 1), 'MMMM yyyy')}`, 105, 29, { align: 'center' });
    
    // Reset text color
    pdf.setTextColor(0, 0, 0);
    
    // Summary Box
    pdf.setFillColor(240, 240, 240);
    pdf.roundedRect(14, 42, 182, 20, 3, 3, 'F');
    pdf.setFontSize(11);
    pdf.setFont(undefined, 'bold');
    pdf.text('Payroll Summary', 20, 50);
    pdf.setFont(undefined, 'normal');
    pdf.setFontSize(10);
    pdf.text(`Total Employees: ${payrollData.totalEmployees}`, 20, 57);
    pdf.text(`Generated by: ${payrollData.generatedBy}`, 120, 57);

    // Table data
    const tableData = payrollData.payroll.map(p => [
      p.employeeName,
      p.profession,
      p.presentDays,
      p.totalOtHours.toFixed(1),
      formatCurrency(p.daySalary),
      formatCurrency(p.otSalary),
      formatCurrency(p.totalSalary),
    ]);

    pdf.autoTable({
      head: [['Employee', 'Profession', 'Days', 'OT Hrs', 'Day Salary', 'OT Salary', 'Total']],
      body: tableData,
      startY: 70,
      theme: 'striped',
      headStyles: { fillColor: [20, 83, 89], fontSize: 10, fontStyle: 'bold' },
      margin: { left: 14, right: 14 },
    });

    // Total Salary Box
    const finalY = pdf.lastAutoTable.finalY || 70;
    pdf.setFillColor(34, 197, 94);
    pdf.roundedRect(14, finalY + 5, 182, 12, 3, 3, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'bold');
    pdf.text('GRAND TOTAL:', 20, finalY + 13);
    pdf.text(formatCurrency(payrollData.totalAmount), 190, finalY + 13, { align: 'right' });
    
    // Footer
    const footerY = pdf.internal.pageSize.height - 15;
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(`Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 105, footerY, { align: 'center' });
    pdf.text('BAWABT ALMASKAN - Confidential Document', 105, footerY + 5, { align: 'center' });

    pdf.save(`Payroll_${year}-${month}.pdf`);
  };

  // Export Employee List
  const exportEmployeeList = () => {
    const wb = XLSX.utils.book_new();
    
    const data = employees.map(emp => {
      const site = sites.find(s => s.id === emp.siteId);
      return {
        'Employee ID': emp.id,
        'Name': emp.name,
        'Profession': emp.profession,
        'Per Day Salary': emp.perDaySalary,
        'Per Hour Salary': emp.perHourSalary,
        'Site Number': site?.siteNumber || '-',
        'Site Name': site?.siteName || '-',
        'Site Location': site?.location || '-',
        'Status': emp.active ? 'Active' : 'Inactive',
        'Joining Date': emp.joiningDate || '-',
        'Notes': emp.notes || '-',
      };
    });

    const ws = XLSX.utils.json_to_sheet(data);
    XLSX.utils.book_append_sheet(wb, ws, 'Employees');
    XLSX.writeFile(wb, `Employee_List_${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
  };

  // Export Individual Payroll - Professional Design
  const exportIndividualPayroll = (employeeData) => {
    const pdf = new jsPDF();
    
    // Company Header - Professional Teal
    pdf.setFillColor(20, 83, 89); // Professional teal
    pdf.rect(0, 0, 210, 35, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(20);
    pdf.setFont(undefined, 'bold');
    pdf.text('BAWABT ALMASKAN', 105, 15, { align: 'center' });
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text('REAL ESTATE - Employee Payroll Statement', 105, 22, { align: 'center' });
    pdf.text(`Period: ${format(new Date(year, month - 1), 'MMMM yyyy')}`, 105, 29, { align: 'center' });
    
    // Reset text color
    pdf.setTextColor(0, 0, 0);
    
    // Employee Information Box
    pdf.setFillColor(240, 240, 240);
    pdf.roundedRect(14, 42, 182, 25, 3, 3, 'F');
    pdf.setFontSize(12);
    pdf.setFont(undefined, 'bold');
    pdf.text('Employee Information', 20, 50);
    pdf.setFont(undefined, 'normal');
    pdf.setFontSize(10);
    pdf.text(`Name: ${employeeData.employeeName}`, 20, 57);
    pdf.text(`Profession: ${employeeData.profession}`, 20, 63);
    
    // Attendance Summary Table
    pdf.autoTable({
      startY: 75,
      head: [['Attendance Summary', 'Days/Hours']],
      body: [
        ['Present Days', employeeData.presentDays.toString()],
        ['Absent Days', employeeData.absentDays.toString()],
        ['Half Days', employeeData.halfDays.toString()],
        ['Overtime Hours', employeeData.totalOtHours.toFixed(1)],
      ],
      theme: 'striped',
      headStyles: { fillColor: [34, 197, 94], fontSize: 11, fontStyle: 'bold' },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 140 },
        1: { halign: 'right', cellWidth: 42 }
      },
      margin: { left: 14, right: 14 },
    });
    
    // Salary Breakdown Table
    const finalY = pdf.lastAutoTable.finalY;
    pdf.autoTable({
      startY: finalY + 10,
      head: [['Salary Component', 'Amount']],
      body: [
        ['Basic Salary (Daily)', formatCurrency(employeeData.daySalary)],
        ['Overtime Salary', formatCurrency(employeeData.otSalary)],
      ],
      theme: 'striped',
      headStyles: { fillColor: [20, 83, 89], fontSize: 11, fontStyle: 'bold' },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 140 },
        1: { halign: 'right', cellWidth: 42 }
      },
      margin: { left: 14, right: 14 },
    });
    
    // Total Salary Box
    const salaryY = pdf.lastAutoTable.finalY + 5;
    pdf.setFillColor(34, 197, 94);
    pdf.roundedRect(14, salaryY, 182, 15, 3, 3, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont(undefined, 'bold');
    pdf.text('TOTAL SALARY:', 20, salaryY + 10);
    pdf.text(formatCurrency(employeeData.totalSalary), 190, salaryY + 10, { align: 'right' });
    
    // Sites Worked Table
    if (employeeData.sites && employeeData.sites.length > 0) {
      pdf.setTextColor(0, 0, 0);
      pdf.autoTable({
        startY: salaryY + 22,
        head: [['Site Number', 'Site Name', 'Days Worked']],
        body: employeeData.sites.map(site => [
          site.siteNumber,
          site.siteName,
          site.days.toString()
        ]),
        theme: 'grid',
        headStyles: { fillColor: [14, 165, 233], fontSize: 10 },
        margin: { left: 14, right: 14 },
      });
    }
    
    // Footer
    const footerY = pdf.internal.pageSize.height - 15;
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(`Generated on: ${format(new Date(), 'dd MMM yyyy HH:mm')}`, 105, footerY, { align: 'center' });
    pdf.text('BAWABT ALMASKAN - Confidential Document', 105, footerY + 5, { align: 'center' });

    pdf.save(`Payroll_${employeeData.employeeName.replace(/\s+/g, '_')}_${year}-${month}.pdf`);
  };

  const reports = [
    {
      title: 'Attendance Report',
      description: 'Daily attendance records',
      icon: FileText,
      gradient: 'from-info-light to-info/10',
      iconBg: 'bg-info/10',
      iconColor: 'text-info',
      action: exportAttendanceReport,
      loading: attendanceLoading,
    },
    {
      title: 'Payroll Report',
      description: 'Employee salary breakdown',
      icon: DollarSign,
      gradient: 'from-success-light to-success/10',
      iconBg: 'bg-success/10',
      iconColor: 'text-success',
      action: exportPayrollReport,
      loading: payrollLoading,
    },
    {
      title: 'Employee List',
      description: 'Complete employee database',
      icon: Users,
      gradient: 'from-accent-light to-accent/10',
      iconBg: 'bg-accent/10',
      iconColor: 'text-accent',
      action: exportEmployeeList,
      loading: false,
    },
  ];

  // Calculate stats for display
  const totalAttendance = attendance.length;
  const totalOT = attendance.reduce((sum, att) => sum + (att.otHours || 0), 0);
  const totalPayroll = payrollData?.totalAmount || 0;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
          Reports
        </h1>
        <p className="text-muted-foreground mt-1">
          Generate and export various reports
        </p>
      </div>

      {/* Date Selectors */}
      <Card className="shadow-card border-0">
        <CardContent className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <Label htmlFor="month">Select Month (For Payroll)</Label>
              <Input
                id="month"
                type="month"
                value={selectedMonth}
                onChange={(e) => setSelectedMonth(e.target.value)}
                max={format(new Date(), 'yyyy-MM')}
              />
            </div>
            <div>
              <Label htmlFor="date">Select Date (For Attendance)</Label>
              <Input
                id="date"
                type="date"
                value={reportDate}
                onChange={(e) => setReportDate(e.target.value)}
                max={format(new Date(), 'yyyy-MM-dd')}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="shadow-3d border-0 overflow-hidden hover:-translate-y-1 transition-all">
          <div className="h-2 bg-gradient-to-r from-info-light to-info/10" />
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Attendance</p>
                <p className="text-3xl font-bold">{totalAttendance}</p>
              </div>
              <div className="bg-info/10 p-3 rounded-xl">
                <Calendar className="h-6 w-6 text-info" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-3d border-0 overflow-hidden hover:-translate-y-1 transition-all">
          <div className="h-2 bg-gradient-to-r from-success-light to-success/10" />
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">OT Hours</p>
                <p className="text-3xl font-bold">{totalOT.toFixed(1)}</p>
              </div>
              <div className="bg-success/10 p-3 rounded-xl">
                <Clock className="h-6 w-6 text-success" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-3d border-0 overflow-hidden hover:-translate-y-1 transition-all">
          <div className="h-2 bg-gradient-to-r from-accent-light to-accent/10" />
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">Total Payroll</p>
                <p className="text-3xl font-bold">{formatCurrency(totalPayroll)}</p>
              </div>
              <div className="bg-accent/10 p-3 rounded-xl">
                <DollarSign className="h-6 w-6 text-accent" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Export Reports */}
      <div>
        <h2 className="text-xl font-semibold mb-4">Export Reports</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {reports.map((report, index) => {
            const Icon = report.icon;
            return (
              <Card 
                key={index}
                className="shadow-3d border-0 overflow-hidden hover:-translate-y-1 transition-all"
              >
                <div className={`h-2 bg-gradient-to-r ${report.gradient}`} />
                <CardContent className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div className={`${report.iconBg} p-3 rounded-xl`}>
                      <Icon className={`h-6 w-6 ${report.iconColor}`} />
                    </div>
                  </div>
                  <h3 className="font-semibold text-lg mb-1">{report.title}</h3>
                  <p className="text-sm text-muted-foreground mb-4">{report.description}</p>
                  <Button
                    onClick={report.action}
                    className="w-full"
                    disabled={report.loading}
                  >
                    <Download className="h-4 w-4 mr-2" />
                    {report.loading ? 'Loading...' : 'Download'}
                  </Button>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>

      {/* Individual Payroll Reports */}
      {payrollData && payrollData.payroll && payrollData.payroll.length > 0 && (
        <Card className="shadow-card border-0">
          <CardHeader>
            <CardTitle>Individual Payroll Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {payrollData.payroll.map((emp, index) => (
                <div 
                  key={index} 
                  className="flex items-center justify-between p-4 bg-muted/50 rounded-lg hover:bg-muted transition-colors"
                >
                  <div>
                    <p className="font-medium">{emp.employeeName}</p>
                    <p className="text-sm text-muted-foreground">{emp.profession}</p>
                    <p className="text-sm font-semibold text-primary mt-1">
                      {formatCurrency(emp.totalSalary)}
                    </p>
                  </div>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => exportIndividualPayroll(emp)}
                  >
                    <Download className="h-4 w-4 mr-1" />
                    PDF
                  </Button>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
